name: pyEsmFinal
dependencies:
  - python=3.8
  - pip:
      - scipy
      - numpy
      - flask
      - requests
      - flask_apscheduler
      - pysmiles
      - pytest
  - conda:
      - openbabel